api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    # The title of the API.
    title: 'API Escape Game'
    # The description of the API.
    description: "Service web pour les logiciels leger de l'espace game"
    # The version of the API.
    version: '1.0.0'
